name: Build ClintMailDelivery

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Add build environment
        uses: Pathoschild/SMAPI-ModBuildWorkflow/add-build-environment@v0

      - name: Restore packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: ClintMailDelivery
          path: bin/Release/net6.0/ClintMailDelivery.dll